# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-30 23:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CookieDisclaimer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default="I've set a cookie so that I could notify you of it using this cookie notification bar. You're welcome.")),
                ('accept_text', models.CharField(default='Nice bamboozle. Cheers!', max_length=100)),
                ('decline_text', models.CharField(default='0/10 no https. Let me out', max_length=100)),
                ('back_url', models.URLField(default='http://livepuppycam.com/')),
            ],
            options={
                'verbose_name_plural': 'Cookie Disclaimer',
            },
        ),
    ]
