# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-30 23:25
from __future__ import unicode_literals

import colorful.fields
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filer', '0007_auto_20161016_1055'),
    ]

    operations = [
        migrations.CreateModel(
            name='Microformat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('workplace', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('last_update', models.DateField(blank=True, null=True)),
                ('thumb', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='filer.Image')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('color', colorful.fields.RGBColorField()),
                ('icon', models.CharField(choices=[['icon-facebook', 'Facebook'], ['icon-github', 'Github'], ['icon-linkedin', 'LinkedIn'], ['icon-youtube', 'Youtube'], ['icon-stackoverflow', 'Stackoverflow'], ['icon-soundcloud', 'Soundcloud']], max_length=50)),
                ('order', models.SmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
